# Generated by Django 2.2.3 on 2021-08-19 06:59

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('imei', models.CharField(max_length=255)),
                ('license_plate', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('title', models.CharField(max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('build_year', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_icon', models.CharField(blank=True, max_length=200, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('chassis_number', models.CharField(blank=True, max_length=100, null=True)),
                ('engine_number', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('body_type', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel_capacity', models.DecimalField(decimal_places=4, default=40, max_digits=9)),
                ('kpl', models.DecimalField(blank=True, decimal_places=4, default=8, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fuel_reading_status', models.BooleanField(default=False)),
                ('formula', models.TextField(blank=True, null=True)),
                ('refuel_percentage_threshold', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('refuel_ltr_threshold', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('leakage_percentage_threshold', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('leakage_ltr_threshold', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('fuel_speed_threshold', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('fuel_data_delay', models.IntegerField(blank=True, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=20, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=20, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TripInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trip_date', models.DateField()),
                ('trip_time', models.TimeField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip_management.Vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('invoice_id', models.CharField(max_length=255)),
                ('delivery_status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Scheduled'), (3, 'OnDelivery'), (4, 'Delivered')], default=1)),
                ('estimated_delivery_date', models.DateField(blank=True, null=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('delivery_address', models.CharField(max_length=255)),
                ('customer_phone_no', models.CharField(max_length=15)),
                ('remarks', models.CharField(max_length=255)),
                ('sales_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip_management.SalesPoint')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('nid_front_key', models.CharField(blank=True, max_length=100, null=True)),
                ('nid_back_key', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('driving_license_front_key', models.CharField(blank=True, max_length=100, null=True)),
                ('driving_license_back_key', models.CharField(blank=True, max_length=100, null=True)),
                ('license_issue_date', models.DateField(blank=True, null=True)),
                ('license_expiry_date', models.DateField(blank=True, null=True)),
                ('license_number', models.CharField(max_length=30, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('sequence', models.PositiveSmallIntegerField()),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trip_management.Invoice')),
                ('trip_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip_management.TripInfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
