# Generated by Django 2.2.3 on 2021-08-19 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='driving_license_back_key',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='driving_license_front_key',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='nid_back_key',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='nid_front_key',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='user',
        ),
    ]
