# Generated by Django 2.2.3 on 2021-08-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_management', '0002_auto_20210819_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
