# Generated by Django 2.2.3 on 2021-09-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_management', '0003_driver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespoint',
            name='sales_person',
            field=models.CharField(default='Feroz', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salespoint',
            name='showroom_code',
            field=models.CharField(default='DHK03', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
