# Generated by Django 2.2.3 on 2021-10-19 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_management', '0006_auto_20211017_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='salespoint',
            name='sales_person',
        ),
        migrations.AddField(
            model_name='invoice',
            name='selling_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sales_person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trip_management.SalesPerson'),
            preserve_default=False,
        ),
    ]
