# Generated by Django 2.2.3 on 2021-10-20 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_management', '0007_auto_20211019_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripinfo',
            name='trip_time',
        ),
        migrations.AddField(
            model_name='tripinfo',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trip_management.Driver'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripinfo',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trip_management.WareHouse'),
            preserve_default=False,
        ),
    ]
