# Generated by Django 2.2.3 on 2021-10-27 04:00

from django.db import migrations, models

data = []
def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    destinations = apps.get_model('trip_management', "destinations")
    destinations_data = destinations.objects.all()
    for data in destinations_data:
        des_dict = {
            "id": data.invoice.id,
            "lon": data.lon,
            "lat": data.lat,
        }
        data.append(des_dict)

def reverse_func(apps, schema_editor):
    invoice = apps.get_model('trip_management', "invoice")

    for d in data:
        invoice.objects.filter(pk=d['id']).update(lon=d['lon'], lat=d['lat'])

class Migration(migrations.Migration):

    dependencies = [
        ('trip_management', '0008_auto_20211020_0756'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
        migrations.RemoveField(
            model_name='destinations',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='destinations',
            name='lon',
        ),
        migrations.AddField(
            model_name='invoice',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RunPython(reverse_func),
    ]
