# Generated by Django 2.2.3 on 2021-11-25 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_management', '0009_auto_20211027_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='sales_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trip_management.SalesPerson'),
        ),
    ]
