# Generated by Django 2.2.3 on 2021-11-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_management', '0010_auto_20211125_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespoint',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='salespoint',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
