# Generated by Django 2.2.3 on 2021-12-04 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_management', '0011_auto_20211125_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinations',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='trip_management.Invoice'),
        ),
    ]
