# Generated by Django 2.2.3 on 2021-12-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_management', '0012_auto_20211204_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='phone_no',
            field=models.CharField(default='01700000000', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripinfo',
            name='trip_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Scheduled'), (2, 'Started'), (3, 'Complete')], default=1),
        ),
    ]
