# Generated by Django 2.2.3 on 2021-12-06 12:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_management', '0013_auto_20211205_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destinations',
            name='reach_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripinfo',
            name='current_sequence',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tripinfo',
            name='trip_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripinfo',
            name='trip_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripinfo',
            name='vehicle_location',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='delivery_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Scheduled'), (3, 'OnDelivery'), (4, 'Unloading'), (5, 'Delivered')], default=1),
        ),
    ]
