# Generated by Django 2.2.3 on 2021-12-14 11:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_management', '0014_auto_20211206_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='route_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destinations',
            name='route_history',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='tripinfo',
            name='return_route_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripinfo',
            name='return_route_history',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
    ]
