# Generated by Django 2.2.3 on 2021-12-21 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_management', '0015_auto_20211214_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('salary', models.FloatField(default=0.0)),
                ('designation', models.CharField(default='Delivery Man', max_length=255)),
                ('duty_hours', models.PositiveSmallIntegerField(default=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='designation',
            field=models.CharField(default='Driver', max_length=255),
        ),
        migrations.AddField(
            model_name='driver',
            name='duty_hours',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='driver',
            name='salary',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='TripDeliveryMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryman', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trip_management.DeliveryMan')),
                ('trip_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip_management.TripInfo')),
            ],
        ),
        migrations.AddField(
            model_name='deliveryman',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trip_management.Driver'),
        ),
    ]
