# Generated by Django 2.2.3 on 2021-12-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_management', '0016_auto_20211221_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespoint',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salespoint',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
