# Generated by Django 2.2.3 on 2022-01-09 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_management', '0018_invoice_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='sms_status',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trip_management.Invoice'),
        ),
    ]
