# Generated by Django 2.2.3 on 2021-12-08 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_management', '0014_auto_20211206_1209'),
        ('user', '0002_auto_20210819_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salespoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trip_management.SalesPoint'),
        ),
    ]
