# Generated by Django 2.2.3 on 2021-12-22 19:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trip_management', '0016_auto_20211221_0227'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyLogBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('logdate', models.DateTimeField()),
                ('gatepass', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True)),
                ('total_delivery_value_dp', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('total_delivery_value_sp', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('total_delivery_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('other_delivery_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('dp_percent', models.FloatField(default=0.0)),
                ('sp_percent', models.FloatField(default=0.0)),
                ('fuel_reserve', models.FloatField(default=0.0)),
                ('fuel_purchase', models.FloatField(default=0.0)),
                ('start_fuel', models.FloatField(default=0.0)),
                ('fuel_consumption', models.FloatField(default=0.0)),
                ('end_fuel', models.FloatField(default=0.0)),
                ('fuel_cost', models.FloatField(default=0.0)),
                ('toll_fuel_cost', models.FloatField(default=0.0)),
                ('others_fuel_cost', models.FloatField(default=0.0)),
                ('total_vehicle_cost', models.FloatField(default=0.0)),
                ('start_vehicle_cost', models.FloatField(default=0.0)),
                ('end_vehicle_cost', models.FloatField(default=0.0)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trip_management.Vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_start', models.DateTimeField(blank=True, null=True)),
                ('duty_end', models.DateTimeField(blank=True, null=True)),
                ('ot_start', models.DateTimeField(blank=True, null=True)),
                ('total_ot', models.TimeField(blank=True, null=True)),
                ('ot_payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('tiffin', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('ot_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('hotel', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('deliveryman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trip_management.DeliveryMan')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trip_management.Driver')),
                ('duty_log_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_management.DutyLogBook')),
            ],
        ),
    ]
