# Generated by Django 2.2.3 on 2021-12-26 16:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutylogbook',
            name='destinations',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='dutylogbook',
            name='total_allowance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dutylogbook',
            name='total_distance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dutylogbook',
            name='total_hotel',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dutylogbook',
            name='total_ot_allowance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dutylogbook',
            name='total_ot_payment',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dutylogbook',
            name='total_tiffin',
            field=models.FloatField(default=0.0),
        ),
    ]
