# Generated by Django 2.2.3 on 2021-12-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_management', '0002_auto_20211226_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutylogbook',
            name='cost_per_kilo',
            field=models.FloatField(default=0.0),
        ),
    ]
