# Generated by Django 2.2.3 on 2021-12-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_management', '0003_dutylogbook_cost_per_kilo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutylogbook',
            name='total_one_day_salary',
            field=models.FloatField(default=0.0),
        ),
    ]
